In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   str
 2   title         6234 non-null   str
 3   director      4265 non-null   str
 4   cast          5664 non-null   str
 5   country       5758 non-null   str
 6   date_added    6223 non-null   str
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   str
 9   duration      6234 non-null   str
 10  listed_in     6234 non-null   str
 11  description   6234 non-null   str
dtypes: int64(2), str(10)
memory usage: 584.6 KB

In [4]:
df.isnull().sum()

show_id            0
type               0
title              0
director        1969
cast             570
country          476
date_added        11
release_year       0
rating            10
duration           0
listed_in          0
description        0
dtype: int64

In [5]:
df.isnull().sum()/len(df)*100

show_id          0.000000
type             0.000000
title            0.000000
director        31.584857
cast             9.143407
country          7.635547
date_added       0.176452
release_year     0.000000
rating           0.160411
duration         0.000000
listed_in        0.000000
description      0.000000
dtype: float64

In [8]:
df[['director','cast','country','date_added','rating']]=df[['director','cast','country','date_added','rating']].fillna(df[['director','cast','country','date_added','rating']].mode().iloc[0])

In [9]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [13]:
col=df.columns
for i in col:
    print(i)
    print(df[i].unique())

show_id
[81145628 80117401 70234439 ... 80116008 70281022 70153404]
type
<StringArray>
['Movie', 'TV Show']
Length: 2, dtype: str
title
<StringArray>
[    'Norm of the North: King Sized Adventure',
                  'Jandino: Whatever it Takes',
                          'Transformers Prime',
            'Transformers: Robots in Disguise',
                                '#realityhigh',
                                     'Apaches',
                                    'Automata',
          'Fabrizio Copano: Solo pienso en mi',
                                'Fire Chasers',
                                 'Good People',
 ...
                             'Gunslinger Girl',
             'Anthony Bourdain: Parts Unknown',
                                     'Frasier',
                         'La Familia P. Luche',
                'The Adventures of Figaro Pho',
                                    'Kikoriki',
                                'Red vs. Blue',
                                       'Maron',
 'A Young Doctor's Notebook and Other Stories',
                                     'Friends']
Length: 6172, dtype: str
director
<StringArray>
[            'Richard Finn, Tim Maltby',
               'Raúl Campos, Jan Suter',
                     'Fernando Lebrija',
                          'Gabe Ibáñez',
      'Rodrigo Toro, Francisco Schultz',
                    'Henrik Ruben Genz',
                'José Miguel Contreras',
                     'Daniel Alfredson',
          'Munjal Shroff, Tilak Shetty',
                         'Tilak Shetty',
 ...
                       'Stefan Brogren',
                      'Peter McDonnell',
                     'Tony Collingwood',
                        'Yasuhiro Irie',
                          'James Hawes',
              'Jung-ah Im, Seung-uk Jo',
                      'Andy Devonshire',
 'Vikramaditya Motwane, Anurag Kashyap',
                           'Jung-ah Im',
                            'Onur Ünlü']
Length: 3301, dtype: str
cast
<StringArray>
[                                                                                                                                      'Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson',
                                                                                                                                                                                                                                                                  'Jandino Asporaat',
                                                                                                'Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle',
                                                                                                                                                          'Will Friedle, Darren Criss, Constance Zimmer, Khary Payton, Mitchell Whitfield, Stuart Allan, Ted McGinley, Peter Cullen',
                                                                                                          'Nesta Cooper, Kate Walsh, John Michael Higgins, Keith Powers, Alicia Sanz, Jake Borelli, Kid Ink, Yousef Erakat, Rebekah Graf, Anne Winters, Peter Gilroy, Patrick Davis',
                                                                                                                                                                                                     'Alberto Ammann, Eloy Azorín, Verónica Echegui, Lucía Jiménez, Claudia Traisac',
                                                                                                                            'Antonio Banderas, Dylan McDermott, Melanie Griffith, Birgitte Hjort Sørensen, Robert Forster, Christa Campbell, Tim McInnerny, Andy Nyman, David Ryall',
                                                                                                                                                                                                                                                                   'Fabrizio Copano',
                                                                                                                                                                                                                                                                'David Attenborough',
                                                                                                                    'James Franco, Kate Hudson, Tom Wilkinson, Omar Sy, Sam Spruell, Anna Friel, Thomas Arnold, Oliver Dimsdale, Diana Hardcastle, Michael Jibson, Diarmaid Murtagh',
 ...
 'Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Ami Koshimizu, Hidenobu Kiuchi, Mitsuru Miyamoto, Masashi Ebara, Norihiro Inoue, Rie Nakagawa, Masami Iwasaki, Laura Bailey, Luci Christian, Caitlin Glass, Alese Johnson, Monica Rial, Jerry Jewell, Stephanie Young, Mike McFarland',
                                                                                                                                                                                                                                                                  'Anthony Bourdain',
                                                                                                                                                                                             'Kelsey Grammer, Jane Leeves, David Hyde Pierce, Peri Gilpin, John Mahoney, Dan Butler',
                                                                                                                                                   'Eugenio Derbez, Consuelo Duval, Luis Manuel Ávila, Regina Blandón, Miguel Perez, Barbara Torres, Dalilah Polanco, Pierre Angelo',
                                                                                                                                                                                          'Luke Jurevicius, Craig Behenna, Charlotte Hamlyn, Stavroula Mountzouris, Aletheia Burney',
                                                                                                                                                                                                                                                                     'Igor Dmitriev',
                                                                                                                               'Burnie Burns, Jason Saldaña, Gustavo Sorola, Geoff Lazer Ramsey, Joel Heyman, Matt Hullum, Dan Godwin, Kathleen Zuelch, Yomary Cruz, Nathan Zellner',
                                                                                                                                                                                                                 'Marc Maron, Judd Hirsch, Josh Brener, Nora Zehetner, Andy Kindler',
                                                                                                                                             'Daniel Radcliffe, Jon Hamm, Adam Godley, Christopher Godwin, Rosie Cavaliero, Vicki Pepperdine, Margaret Clunie, Tim Steed, Shaun Pye',
                                                                                                                                                                                        'Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc, Matthew Perry, David Schwimmer']
Length: 5469, dtype: str
country
<StringArray>
[                  'United States, India, South Korea, China',
                                             'United Kingdom',
                                              'United States',
                                                      'Spain',
                     'Bulgaria, United States, Spain, Canada',
                                                      'Chile',
             'United States, United Kingdom, Denmark, Sweden',
        'Netherlands, Belgium, United Kingdom, United States',
                                            'France, Belgium',
                                     'United States, Uruguay',
 ...
                        'Netherlands, Germany, Italy, Canada',
                                                    'Croatia',
                                            'Finland, France',
                  'Denmark, Singapore, Canada, United States',
                    'United States, Hungary, Ireland, Canada',
                                             'Norway, Sweden',
                            'United States, Mexico, Colombia',
 'United States, Brazil, South Korea, Mexico, Japan, Germany',
                                             'Italy, Germany',
                                  'Cyprus, Austria, Thailand']
Length: 554, dtype: str
date_added
<StringArray>
['September 9, 2019', 'September 9, 2016', 'September 8, 2018',
 'September 8, 2017', 'September 8, 2015', 'September 7, 2018',
 'September 7, 2017', 'September 6, 2019', 'September 6, 2018',
 'September 6, 2017',
 ...
   ' April 15, 2018',   ' April 15, 2017',   ' April 14, 2017',
   ' April 13, 2019',   ' April 13, 2018',   ' April 11, 2019',
   ' April 10, 2019',    ' April 1, 2019',    ' April 1, 2016',
    ' April 1, 2014']
Length: 1524, dtype: str
release_year
[2019 2016 2013 2017 2014 2015 2009 2012 2010 2018 2011 2004 2000 1983
 1982 2006 2005 2002 1997 2008 2007 2003 1981 1991 1994 1988 1976 1973
 1974 1989 1986 1984 1978 1998 1972 1979 1960 1959 2001 1995 1992 1990
 1975 1985 1980 1970 1996 1967 1999 1987 1968 1993 2020 1958 1965 1956
 1962 1955 1977 1945 1946 1942 1944 1947 1943 1969 1954 1966 1971 1964
 1925 1963]
rating
<StringArray>
[   'TV-PG',    'TV-MA', 'TV-Y7-FV',    'TV-Y7',    'TV-14',        'R',
     'TV-Y',       'NR',    'PG-13',     'TV-G',       'PG',        'G',
       'UR',    'NC-17']
Length: 14, dtype: str
duration
<StringArray>
[    '90 min',     '94 min',   '1 Season',     '99 min',    '110 min',
     '60 min',     '78 min',     '95 min',     '58 min',     '62 min',
 ...
  '4 Seasons',  '8 Seasons',  '6 Seasons',  '9 Seasons', '14 Seasons',
 '10 Seasons', '12 Seasons', '15 Seasons', '11 Seasons', '13 Seasons']
Length: 201, dtype: str
listed_in
<StringArray>
[                               'Children & Family Movies, Comedies',
                                                   'Stand-Up Comedy',
                                                          'Kids' TV',
                                                          'Comedies',
 'Crime TV Shows, International TV Shows, Spanish-Language TV Shows',
                 'International Movies, Sci-Fi & Fantasy, Thrillers',
                                   'Docuseries, Science & Nature TV',
                                     'Action & Adventure, Thrillers',
                  'Action & Adventure, Dramas, International Movies',
                                          'Children & Family Movies',
 ...
               'Crime TV Shows, TV Action & Adventure, TV Thrillers',
                'Crime TV Shows, International TV Shows, Reality TV',
                              'Crime TV Shows, TV Dramas, TV Horror',
                                   'Kids' TV, TV Action & Adventure',
                   'TV Comedies, TV Sci-Fi & Fantasy, Teen TV Shows',
                          'Classic & Cult TV, Kids' TV, TV Comedies',
                          'British TV Shows, TV Comedies, TV Dramas',
               'Romantic TV Shows, TV Action & Adventure, TV Dramas',
                                 'TV Comedies, TV Dramas, TV Horror',
                             'Reality TV, Spanish-Language TV Shows']
Length: 461, dtype: str
description
<StringArray>
[          'Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.',
      'Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of "Sex on Fire" in his comedy show.',
           'With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron.',
                         'When a prison ship crash unleashes hundreds of Decepticons on Earth, Bumblebee leads a new Autobot force to protect humankind.',
   'When nerdy high schooler Dani finally attracts the interest of her longtime crush, she lands in the cross hairs of his ex, a social media celebrity.',
               'A young journalist is forced into a life of crime to save his father and family in this series based on the novel by Miguel Sáez Carral.',
  'In a dystopian future, an insurance adjuster for a tech company investigates a robot killed for violating protocol and discovers a global conspiracy.',
  'Fabrizio Copano takes audience participation to the next level in this stand-up set while reflecting on sperm banks, family WhatsApp groups and more.',
    'As California's 2016 fire season rages, brave backcountry firefighters race to put out the flames, protect homes and save lives in this docuseries.',
                 'A struggling couple can't believe their luck when they find a stash of money in the apartment of a neighbor who was recently murdered.',
 ...
        'This CNN original series has chef Anthony Bourdain traveling to extraordinary locations around the globe to sample a variety of local cuisines.',
  'Frasier Crane is a snooty but lovable Seattle psychiatrist who dispenses advice on his call-in radio show while ignoring it in his own relationships.',
                    'This irreverent sitcom featues Ludovico, Federica and their three children Bibi, Junior and Ludoviquito, living in Ciudad P. Luche.',
 'Imagine your worst fears, then multiply them: Figaro is a boy with any number of phobias and a highly quirky and imaginative way of dealing with them.',
     'A wacky rabbit and his gang of animal pals have fun solving problems, sharing stories and exploring their sometimes magical, always special world.',
   'This parody of first-person shooter games, military life and science-fiction films centers on a civil war fought in the middle of a desolate canyon.',
 'Marc Maron stars as Marc Maron, who interviews fellow comedians for his popular podcast, only to reveal more about his own neuroses and relationships.',
     'Nursery rhymes and original music for children accompanied by bright, playful animation engage and educate about numbers, shapes, colors and more.',
     'Set during the Russian Revolution, this comic miniseries is based on a doctor's memories of his early career working in an out-of-the-way village.',
      'This hit sitcom follows the merry misadventures of six 20-something pals as they navigate the pitfalls of work, life and love in 1990s Manhattan.']
Length: 6226, dtype: str

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   str
 2   title         6234 non-null   str
 3   director      6234 non-null   str
 4   cast          6234 non-null   str
 5   country       6234 non-null   str
 6   date_added    6234 non-null   str
 7   release_year  6234 non-null   int64
 8   rating        6234 non-null   str
 9   duration      6234 non-null   str
 10  listed_in     6234 non-null   str
 11  description   6234 non-null   str
dtypes: int64(2), str(10)
memory usage: 584.6 KB

In [15]:
df[df.duplicated()].shape

(0, 12)

In [20]:
df['date_added']=pd.to_datetime(df['date_added'].str.strip(),format='%B %d, %Y')

In [21]:
df.dtypes

show_id                  int64
type                       str
title                      str
director                   str
cast                       str
country                    str
date_added      datetime64[us]
release_year             int64
rating                     str
duration                   str
listed_in                  str
description                str
dtype: object

In [22]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,"Raúl Campos, Jan Suter",Jandino Asporaat,United Kingdom,2016-09-09,2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,"Raúl Campos, Jan Suter","Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09-08,2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,"Raúl Campos, Jan Suter","Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09-08,2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09-08,2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [23]:
df.to_csv("clean_netflix_titles_data.csv")